# Generated by Django 5.2.11 on 2026-02-20 15:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="provider",
            field=models.CharField(
                default="local",
                help_text="로그인 제공자 (local/google/kakao)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="provider_uid",
            field=models.CharField(
                blank=True,
                help_text="소셜 제공자 유저 고유 ID",
                max_length=255,
                null=True,
            ),
        ),
    ]
